logging:
  level:
    root: WARN
    es.upm.miw: DEBUG

app:
  hosting: render

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: create
  # Valores creados en Render → Databases → Database → Connect
  # actualizado
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true