name: CD PostgreSQL

on:
  push:
    branches:
      - master

jobs:
  cd:
    name: Deploy Docker Postgres on AWS Lightsail
    runs-on: ubuntu-22.04

    steps:
      - name: 🚀 Deploy on AWS Lightsail
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP_MAIN }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER_MAIN }}
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY_MAIN }}
          script: |
            docker rm -f postgres || true
            docker network create devopsNet || true
            docker run -d \
              --name postgres \
              --restart always \
              --network devopsNet \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              postgres:15.10